---
- name: Update packages and clean
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 86400
    autoremove: "{{ role_auroremove }}"
    clean: "{{ role_clean }}"
