---
- name: Install and set TLP power saving
  hosts: all
  gather_facts: false

  vars_files:
    - ../vars/vars.yaml

  tasks:
    - name: Enable TLP service
      ansible.builtin.service:
        name: tlp
        enabled: yes
        masked: no
      become: true

    - name: Mask rfkill service
      ansible.builtin.systemd:
        name: systemd-rfkill.service
        masked: yes
      become: true

    - name: Mask rfkill socket
      ansible.builtin.systemd:
        name: systemd-rfkill.socket
        masked: yes
      become: true
