---
- name: Configure wireguard
  hosts: all
  gather_facts: no

  vars_files:
    - ../vars/vars.yaml

  tasks:
    - name: Create Wireguard genkey
      ansible.builtin.shell:  genkey | tee /etc/wireguard/private.key
      args:
        creates: /etc/wireguard/private.key
      become: true

    - name: Set file ownership of key
      ansible.builtin.file:
        path: /etc/wireguard/private.key
        mode: '0600'
      become: true

    - name: Create Wireguard genkey
      ansible.builtin.shell:  cat /etc/wireguard/private.key | wg pubkey | tee /etc/wireguard/public.key
      args:
        creates: /etc/wireguard/public.key
      become: true

    - name: Set Wireguard config
      ansible.builtin.copy:
        src: "../config/wg0.conf"
        dest: /etc/wireguard/wg0.conf
        mode: "0600"
      become: true

    - name: Enable Wireguard service wg0
      ansible.builtin.service:
        name: wg-quick@wg0
        enabled: yes
      become: true

    - name: Set file ownership of resolvconf
      ansible.builtin.file:
        path: /usr/sbin/resolvconf.openresolv
        mode: '0755'
      become: true
