---
- name: Configure wireguard
  hosts: all
  gather_facts: false

  vars_files:
    - ../vars/vars.yaml

  tasks:
    - name: Ensure Wireguard config is present
      ansible.builtin.template:
        src: ../templates/wg0.j2
        dest: /etc/wireguard/wg0.conf
        mode: "0600"
      become: true

    - name: Set file ownership of resolvconf
      ansible.builtin.file:
        path: /usr/sbin/resolvconf.openresolv
        mode: "0755"
      become: true
