---
- name: Install Pi-hole
  hosts: pi_hole

  handlers:
    - name: Restart unbound
      ansible.builtin.service:
        name: unbound
        state: restarted

    - name: Pihole enable
      ansible.builtin.command: pihole enable && pihole restartdns

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Update apt packages
      ansible.builtin.apt:
        name: ¨*¨
        state: latest

  tasks:
    - name: Ensure Curl is installed
      ansible.builtin.apt:
        name:
          - unbound
        state: present

    - name: Copy setup vars file to remote
      ansible.builtin.copy:
        src: ./setupVars.conf
        dest: /etc/pihole/setupVars.conf
        mode: "0644"

    - name: Copy unbound config file to remote
      ansible.builtin.copy:
        src: ./unbound.conf
        dest: /etc/unbound/unbound.conf.d/pi-hole.conf
        mode: "0644"
      notify: Restart unbound

    - name: Ensure root hints file for unbound exist
      ansible.builtin.get_url:
        url: https://www.internic.net/domain/named.root
        dest: /var/lib/unbound/root.hints
        force: true
        mode: "0644"

    - name: Get Pi-hole install script with exectution
      ansible.builtin.get_url:
        url: https://install.pi-hole.net
        dest: /src/pihole/install.sh
        force: true
        mode: "0755"

    - name: Run Pi-hole to ensure it is installed otherwise install
      ansible.builtin.command: pihole
      register: pihole_installed
      changed_when: pihole_installed.rc != 0

    - name: Run Pi-hole install script
      ansible.builtin.command: /src/pihole/install.sh --unattended
      when: pihole_installed.rc != 0
      notify: Pihole enable
