---
- name: Install SMB share
  hosts: smb_share

  vars_files:
    - vars.yml

  vars_prompt:
    - name: sambauser_password
      prompt: What is your samba user password?
      private: true

    - name: sambauser_password_repeat
      prompt: Repeat your samba user password?
      private: true

  pre_tasks:
    - name: Make sure passwords are the same
      ansible.builtin.fail:
        msg: Passwords do not match
      when: not sambauser_password == sambauser_password_repeat
      run_once: true

    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Update apt packages
      ansible.builtin.apt:
        name: ¨*¨
        state: latest

  tasks:
    - name: Ensure samba is installed
      ansible.builtin.apt:
        name:
          - samba
        state: present

    - name: Ensure samba group exists
      ansible.builtin.group:
        name: "{{ sambauser_group }}"
        state: present

    - name: Ensure samba user exists
      ansible.builtin.user:
        name: "{{ sambauser_name }}"
        group: "{{ sambauser_group }}"
        password: "{{ sambauser_password | password_hash('sha512') }}"
        state: present

    - name: Ensure share folder exists
      ansible.builtin.file:
        path: /share
        state: directory
        owner: "{{ sambauser_name }}"
        group: "{{ sambauser_group }}"
        mode: "0664"

    - name: Ensure file share folders exist
      ansible.builtin.file:
        path: /share/file-share
        state: directory
        owner: "{{ sambauser_name }}"
        group: "{{ sambauser_group }}"
        mode: "0664"

    - name: Ensure file share folders exist
      ansible.builtin.file:
        path: /share/video-share
        state: directory
        owner: "{{ sambauser_name }}"
        group: "{{ sambauser_group }}"
        mode: "0664"

    - name: Copy smb config to remote
      ansible.builtin.file:
        src: ./smb.conf
        dest: /etc/samba/smb.conf
        mode: "0664"

    - name: Ensure smbd service is started and enabled
      ansible.builtin.service:
        name: smbd
        state: started
        enabled: true
