---
- name: Install SMB share
  hosts: all

  vars_files:
    - vars.yaml
    - vars-private.yaml

  pre_tasks:
    - name: Update cache if needed (Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update packages
      ansible.builtin.package:
        name: "*"
        state: latest

  tasks:
    - name: Ensure samba is installed
      ansible.builtin.package:
        name:
          - samba
        state: present

    - name: Ensure samba user group exists
      ansible.builtin.group:
        name: "{{ sambauser_name }}"
        gid: 1000
        state: present

    - name: Ensure mount group exists
      ansible.builtin.group:
        name: "{{ mountuser_name }}"
        gid: 3500
        state: present

    - name: Ensure samba user exists
      ansible.builtin.user:
        name: "{{ sambauser_name }}"
        group: "{{ sambauser_name }}"
        groups: "{{ mountuser_name }}"
        uid: 1000
        create_home: false
        shell: /usr/sbin/nologin
        # password: "{{ sambauser_password | password_hash(hashtype='sha512', salt=sambauser_salt) }}"
        state: present

    - name: Ensure mount user exists
      ansible.builtin.user:
        name: "{{ mountuser_name }}"
        group: "{{ mountuser_name }}"
        uid: 3500
        create_home: false
        shell: /usr/sbin/nologin
        state: present

    - name: Ensure root is in mount group
      ansible.builtin.user:
        name: root
        groups: "{{ mountuser_name }}"
        state: present

    - name: Ensure share folder exists
      ansible.builtin.file:
        path: /share
        state: directory
        mode: "0775"

    - name: Copy smb config to remote
      ansible.builtin.copy:
        src: ./smb.conf
        dest: /etc/samba/smb.conf
        mode: "0664"

    - name: Ensure smb password is set
      ansible.builtin.shell: "(echo {{ sambauser_password }}; echo {{ sambauser_password }}) | smbpasswd -s -a {{ sambauser_name }}"
      changed_when: false

    - name: Ensure smbd service is started and enabled
      ansible.builtin.service:
        name: smbd
        state: started
        enabled: true
