---
- name: Install SMB share
  hosts: all

  vars_files:
    - vars.yml
    - vars-private.yml

  pre_tasks:
    - name: Update cache if needed (Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update packages
      ansible.builtin.package:
        name: "*"
        state: latest

  tasks:
    - name: Ensure samba is installed
      ansible.builtin.package:
        name:
          - samba
        state: present

    - name: Ensure samba group exists
      ansible.builtin.group:
        name: "{{ sambauser_group }}"
        state: present

    - name: Ensure samba user exists
      ansible.builtin.user:
        name: "{{ sambauser_name }}"
        group: "{{ sambauser_group }}"
        password: "{{ sambauser_password | password_hash(hashtype='sha512', salt=sambauser_salt) }}"
        state: present

    - name: Ensure share folder exists
      ansible.builtin.file:
        path: /share
        state: directory
        owner: "{{ sambauser_name }}"
        group: "{{ sambauser_group }}"
        mode: "0664"

    - name: Ensure file share folders exist
      ansible.builtin.file:
        path: /share/file-share
        state: directory
        owner: "{{ sambauser_name }}"
        group: "{{ sambauser_group }}"
        mode: "0664"

    - name: Ensure file share folders exist
      ansible.builtin.file:
        path: /share/video-share
        state: directory
        owner: "{{ sambauser_name }}"
        group: "{{ sambauser_group }}"
        mode: "0664"

    - name: Copy smb config to remote
      ansible.builtin.copy:
        src: ./smb.conf
        dest: /etc/samba/smb.conf
        mode: "0664"

    - name: Ensure smbd service is started and enabled
      ansible.builtin.service:
        name: smbd
        state: started
        enabled: true
