---
- name: Install SMB share
  hosts: smb_share

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: update apt packages
      apt:
        name: ¨*¨
        state: latest

  tasks:
    - name: Ensure samba is installed
      apt:
        name:
          - samba
        state: present

    - name: Ensure samba group exists
      group:
        name: "{{ sambauser_group }}"
        state: present

    - name: Ensure samba user exists
      user:
        name: "{{ sambauser_name }}"
        group: "{{ sambauser_group }}"
        password: "{{ sambauser_password | password_hash('sha512') }}"
        state: present

    - name: Ensure share folder exists
      file:
        path: /share
        state: directory
        owner: "{{ sambauser_name }}"
        group: "{{ sambauser_group }}"

    - name: Ensure file share folders exist
      file:
        path: /share/file-share
        state: directory
        owner: "{{ sambauser_name }}"
        group: "{{ sambauser_group }}"

    - name: Ensure file share folders exist
      file:
        path: /share/video-share
        state: directory
        owner: "{{ sambauser_name }}"
        group: "{{ sambauser_group }}"

    - name: Copy smb config to remote
      file:
        src: ./smb.conf
        dest: /etc/samba/smb.conf
        mode: "0664"

    - name: Ensure smbd service is started and enabled
      service:
        name: smbd
        state: started
        enabled: true
