---
# Page meta info, like heading, footer text and nav links
pageInfo:
  title: Dashboard
  description: ---REDACTED---

# Optional app settings and configuration
appConfig:
  theme: lissy # dashy-docs, one-dark, lissy
  defaultOpeningMethod: sametab
  hideComponents:
    hideSettings: true
  preventWriteToDisk: true
  statusCheckInterval: 20
  disableConfiguration: true
  webSearch:
    searchEngine: google
    openingMethod: sametab
  customCss: >
    #dashy{
      height:100vh;
      display:flex;
      flex-flow:column
    }
    html[data-theme=lissy] .home{
      flex:1 1 auto;
      padding-bottom:0!important
    }
    .show-btn[data-v-0222a7c0]{
      display:none
    }
    form.normal[data-v-1958a3d0]{
      border-radius:0 0 var(--curve-factor-navbar) var(--curve-factor-navbar)!important
    }
    form.normal label[data-v-1958a3d0]{
      display:none
    }
    form.normal input[data-v-1958a3d0]{
      font-size:23px!important;
      width:300px!important;
      height:1.4rem!important
    }
    .show-hide-container[data-v-0dc5c42a]{
      display:none
    }
    .edit-mode-item{
      display:none
    }
    .opening-method-icon svg{
      display:none
    }
    .tooltip{
      display:none!important
    }
    .indicator[data-v-4b522b5b]{
      cursor:pointer!important
    }
    .item.size-medium .tile-title {
      height:auto
    }
    .item-icon.wrapper-medium {
      display:flex;
      align-items:center;
      padding:5px 0
    }
    .item.size-medium div img {
      margin-bottom:0
    }

# Main content - An array of sections, each containing an array of items
sections:
  - name: Home Network
    icon: fas fa-network-wired
    displayData:
      itemCountX: 2

    items:
      - title: Proxmox VE
        icon: hl-proxmox
        url: ---REDACTED---
        statusCheck: true
        statusCheckUrl: https://192.168.178.100:8006
        statusCheckAllowInsecure: true

      - title: Passbolt
        icon: ---REDACTED---
        url: ---REDACTED---
        statusCheck: true
        statusCheckAcceptCodes: 401

      - title: Portfolio
        url: ---REDACTED---
        icon: fas fa-globe

      - title: Grafana
        icon: hl-grafana
        url: ---REDACTED---
        statusCheck: true

      - title: Pi-Hole
        icon: hl-pihole-unbound
        url: ---REDACTED---
        statusCheck: true

      - title: Wireguard
        icon: hl-wireguard
        url: ---REDACTED---
        statusCheck: true

      - title: Portainer
        icon: hl-portainer
        url: ---REDACTED---
        statusCheck: true

      - title: Jellyfin
        url: ---REDACTED---
        icon: hl-jellyfin
        statusCheck: true

      - title: Sonarr
        url: ---REDACTED---
        icon: hl-sonarr
        statusCheck: true

      - title: Radarr
        url: ---REDACTED---
        icon: hl-radarr
        statusCheck: true

      - title: Prowlarr
        url: ---REDACTED---
        icon: hl-prowlarr
        statusCheck: true

      - title: qBittorrent
        url: ---REDACTED---
        icon: hl-qbittorrent
        statusCheck: true

      - title: Traefik
        url: http://portainer.home:8080/
        icon: hl-traefik
        statusCheck: true
        statusCheckUrl: http://192.168.178.103:8080

      - title: InfluxDB
        url: http://portainer.home:8086/
        icon: hl-influxdb
        statusCheck: true
        statusCheckUrl: http://192.168.178.103:8086

      - title: Proxmox Backup
        icon: hl-proxmox
        url: ---REDACTED---
        statusCheck: true
        statusCheckUrl: https://192.168.178.108:8007
        statusCheckAllowInsecure: true

      - title: FritzBox
        url: http://192.168.178.1/
        icon: hl-avmfritzbox

  - name: Media
    icon: fas fa-tv
    displayData:
      itemCountX: 2

    items:
      - title: Google Calandar
        icon: favicon
        url: https://calendar.google.com/

      - title: Youtube
        icon: hl-youtube-play
        url: https://www.youtube.com/

      - title: Netflix
        icon: favicon
        url: https://www.netflix.com/browse

      - title: Videoland
        icon: favicon
        url: https://v2.videoland.com/

      - title: Spotify
        icon: hl-spotify
        url: https://open.spotify.com/

      - title: iCloud
        icon: favicon
        url: https://www.icloud.com/

      - title: Reddit
        icon: favicon
        url: https://www.reddit.com/

      - title: Linkedin
        icon: hl-linkedin
        url: ---REDACTED---

      - title: IMDB
        icon: favicon
        url: https://www.imdb.com/

  - name: School
    icon: fas fa-graduation-cap
    displayData:
      itemCountX: 2

    items:
      - title: Canvas
        icon: https://www.instructure.com/sites/default/files/image/2021-12/Canvas_logo_single_mark.png
        url: https://canvas.tue.nl/

      - title: Office 365
        icon: favicon
        url: https://www.office.com/

      - title: Osiris
        icon: https://www.caci.nl/wp-content/uploads/2021/03/Osiris_Pyramid_v5.png
        url: https://tue.osiris-student.nl/#/home

      - title: Osiris PlanApp
        icon: https://www.caci.nl/wp-content/uploads/2021/03/Osiris_Pyramid_v5.png
        url: https://tue.osiris-planapp.nl/#/

      - title: Video College
        url: https://videocollege.tue.nl/Mediasite/Showcase/5faaf306ddb04160a674b9709f79809f44
        icon: https://mediasite.com/wp-content/themes/base-child/assets/images/Mediasite-Logo-Mark_Color@2x.png

      - title: Overleaf
        url: https://www.overleaf.com/project
        icon: favicon

      - title: ANS Delft
        icon: favicon
        url: https://ans.app/

      - title: SOWISO
        icon: https://sowiso.nl/favicon.png
        url: https://tue.sowiso.nl/

      - title: Intranet
        icon: https://www.tue.nl/favicon-64.ico
        url: https://tuenl.sharepoint.com/

      - title: TU/e Databases
        icon: hl-bookstack
        url: http://library.tue.nl/AZDatabases/

  - name: Development
    icon: fas fa-code
    displayData:
      itemCountX: 2

    items:
      - title: GitHub
        url: https://github.com/TychoBrouwer?tab=repositories
        icon: hl-github-light

      - title: Cloudflare
        url: https://dash.cloudflare.com/
        icon: hl-cloudflare

      - title: Docker.io
        url: https://hub.docker.com/repositories/tychobrouwer
        icon: hl-docker

      - title: npm
        url: https://www.npmjs.com/~tbrouwer
        icon: favicon

      - title: Font Awesome
        url: https://fontawesome.com/search
        icon: hl-fontawesome

      - title: Windows Blog
        url: https://blogs.windows.com/windows-insider/
        icon: favicon
