---
global:
  scrape_interval: "1m"

scrape_configs:
  - job_name: 'pve'
    static_configs:
      - targets:
        - ---REDACTED---
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.178.103:9221  # PVE exporter.
  - job_name: 'traefik'
    static_configs:
      - targets:
        - 192.168.178.103:8080