---
http:
  serversTransports:
    pve:
      rootCAs:
        - /root/cert-proxmox.crt

    pve-backup:
      insecureSkipVerify: true

  routers:

  services:
    pve:
      loadBalancer:
        serversTransport: "pve"
        servers:
          - url: "https://192.168.178.100:8006/"

    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.178.101:80/"

    wireguard:
      loadBalancer:
        servers:
          - url: "http://192.168.178.102:10086/"

    torrent:
      loadBalancer:
        servers:
          - url: "http://192.168.178.105:8080/"

    website:
      loadBalancer:
        servers:
          - url: "http://192.168.178.106:80/"

    prowlarr:
      loadBalancer:
        servers:
          - url: "http://192.168.178.107:9696/"

    radarr:
      loadBalancer:
        servers:
          - url: "http://192.168.178.107:7878/"

    sonarr:
      loadBalancer:
        servers:
          - url: "http://192.168.178.107:8989/"

    pve-backup:
      loadBalancer:
        serversTransport: "pve-backup"
        servers:
          - url: "https://192.168.178.108:8007/"

    jellyfin:
      loadBalancer:
        servers:
          - url: "http://192.168.178.111:8096/"

    accontroller:
      loadBalancer:
        servers:
          - url: "http://192.168.178.121:5001/"

  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
