---
http:
  serversTransports:
    pve:
      rootCAs:
        - /root/cert-proxmox.crt

  routers:
    pve:
      entryPoints:
        - web
      rule: "Host (`pve.tbrouwer.com`)"
      service: pve

    pihole:
      entryPoints:
        - web
      rule: "PathPrefix(`/admin`) && Host (`pihole.tbrouwer.com`)"
      service: pihole

    pihole_path:
      entryPoints:
        - web
      rule: "Host (`pihole.tbrouwer.com`)"
      middlewares:
        - "addprefix-pihole"
      service: pihole

    wireguard:
      entryPoints:
        - web
      rule: "Host (`wireguard.tbrouwer.com`)"
      service: wireguard

    torrent:
      entryPoints:
        - web
      rule: "Host(`torrent.tbrouwer.com`)"
      service: torrent

    www-website:
      entryPoints:
        - web
      rule: "Host(`www.tbrouwer.com`)"
      service: website

    website:
      entryPoints:
        - web
      rule: "Host(`tbrouwer.com`)"
      middlewares:
        - "www-redirect"
      service: website

    jellyfin:
      entryPoints:
        - web
      rule: "Host(`jellyfin.tbrouwer.com`)"
      service: jellyfin

    accontroller:
      entryPoints:
        - web
      rule: "Host(`accontroller.tbrouwer.com`)"
      service: accontroller

  services:
    pve:
      loadBalancer:
        serversTransport: "pve"
        servers:
          - url: "https://192.168.178.100:8006/"
        # passHostHeader: true

    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.178.101:80/"
        # passHostHeader: true

    wireguard:
      loadBalancer:
        servers:
          - url: "http://192.168.178.102:10086/"
        # passHostHeader: true

    torrent:
      loadBalancer:
        servers:
          - url: "http://192.168.178.105:8080/"
        # passHostHeader: true

    website:
      loadBalancer:
        servers:
          - url: "http://192.168.178.106:80/"
        # passHostHeader: true

    jellyfin:
      loadBalancer:
        servers:
          - url: "http://192.168.178.111:8096/"
        # passHostHeader: true

    accontroller:
      loadBalancer:
        servers:
          - url: "http://192.168.178.121:5001/"
        # passHostHeader: true

  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"

    www-redirect:
      redirectRegex:
        regex: "https://tbrouwer.com/*"
        replacement: "https://www.tbrouwer.com/*"
