---
http:
  serversTransports:
    pve:
      rootCAs:
        - /root/cert-proxmox.crt

  routers:
    pve:
      entryPoints:
        - web
      rule: "Host (`pve.tbrouwer.com`)"
      service: pve

    pihole:
      entryPoints:
        - web
      rule: "Host (`pihole.tbrouwer.com`)"
      middlewares:
        - "addprefix-pihole"
      service: pihole

    wireguard:
      entryPoints:
        - web
      rule: "Host (`wireguard.tbrouwer.com`)"
      service: wireguard

    torrent:
      entryPoints:
        - web
      rule: "Host(`torrent.tbrouwer.com`)"
      service: torrent

    jellyfin:
      entryPoints:
        - web
      rule: "Host(`jellyfin.tbrouwer.com`)"
      service: jellyfin

    accontrollerapi:
      entryPoints:
        - web
      rule: "Host(`accontroller-api.tbrouwer.com`)"
      service: accontrollerapi

    accontrollersocket:
      entryPoints:
        - web
      rule: "Host(`accontroller-socket.tbrouwer.com`)"
      service: accontrollersocket

  services:
    pve:
      loadBalancer:
        serversTransport: "pve"
        servers:
          - url: "https://192.168.178.100:8006/"
        # passHostHeader: true

    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.178.101:80/"
        # passHostHeader: true

    wireguard:
      loadBalancer:
        servers:
          - url: "http://192.168.178.102:10086/"
        # passHostHeader: true

    torrent:
      loadBalancer:
        servers:
          - url: "http://192.168.178.105:8080/"
        # passHostHeader: true

    jellyfin:
      loadBalancer:
        servers:
          - url: "http://192.168.178.111:8096/"
        # passHostHeader: true

    accontrollerapi:
      loadBalancer:
        servers:
          - url: "http://192.168.178.121:5000/"
        # passHostHeader: true

    accontrollersocket:
      loadBalancer:
        servers:
          - url: "http://192.168.178.121:8880/"
        # passHostHeader: true

  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
