---
- name: Start Proxmox containers
  hosts: proxmox

  tasks:
    - name: Ensure containers are started
      ansible.builtin.command: "pct start {{ item }}"
      loop:
        - 101
        - 102
        - 103
        - 104
        - 105
        - 106
        - 107
        - 108
        - 111
        - 112
        - 113
        - 121
      register: container_start_result
      changed_when: "'already running' not in container_start_result.stdout"
      failed_when: false

    - name: Ensure containers have an addressed ip
      ansible.builtin.command: "pct exec {{ item }} dhclient"
      loop:
        - 101
        - 102
        - 103
        - 104
        - 105
        - 106
        - 107
        - 108
        - 111
        - 112
        - 113
        - 121
      register: dhclient_result
      changed_when: "'File exists' not in dhclient_result.stdout"

    - name: Ensure wg-dashboard is running
      ansible.builtin.command: "pct exec 102 systemctl restart wg-dashboard"
      changed_when: false

- name: Ensure containers are updated
  hosts:
    - infrastructure
    - entertainment
    - projects

  tasks:
    - name: Update cache if needed (Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update packages
      ansible.builtin.package:
        name: "*"
        state: latest
