---
- name: Ensure mounted folder exists
  ansible.builtin.file:
    path: "{{ item.src }}"
    state: directory
    recurse: true
    mode: "0775"
    owner: "{{ role_mountuser_name }}"
    group: "{{ role_mountuser_group }}"
  with_items: "{{ role_mounted_folders }}"

- name: Add idmap to lxc config
  ansible.builtin.blockinfile:
    path: /etc/pve/lxc/{{ role_container_id }}.conf
    block: |
      lxc.idmap: u 0 100000 {{ role_mountuser_uid }}
      lxc.idmap: u {{ role_mountuser_uid }} {{ role_mountuser_uid }} 1
      lxc.idmap: u {{ role_mountuser_uid + 1 }} {{ role_mountuser_uid + 100001 }} {{ 165536 - role_mountuser_uid - 100001 }}
      lxc.idmap: g 0 100000 {{ role_mountuser_gid }}
      lxc.idmap: g {{ role_mountuser_gid }} {{ role_mountuser_gid }} 1
      lxc.idmap: g {{ role_mountuser_gid + 1 }} {{ role_mountuser_gid + 100001 }} {{ 165536 - role_mountuser_gid - 100001 }}
  notify: Restart lxc

- name: Add mounts to lxc config
  ansible.builtin.lineinfile:
    path: /etc/pve/lxc/{{ role_container_id }}.conf
    line: "mp{{ idx }}: {{ item.src }},mp={{ item.dest }}"
  loop: "{{ role_mounted_folders }}"
  loop_control:
    index_var: idx
  notify: Restart lxc
