---
- name: Update all servers
  hosts: all

  tasks:
    - name: Update apt cache if needed
      apt: 
        update_cache: true
        cache_valid_time: 3600

    - name: update apt packages
      apt:
        name: ¨*¨
        state: latest
