---
- name: Update all servers
  hosts: all

  tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Update apt packages
      ansible.builtin.apt:
        name: ¨*¨
        state: latest
