---
- name: Setup torrent client
  hosts: all

  vars_files:
    - vars.yml
    - vars-private.yml

  pre_tasks:
    - name: Update cache if needed (Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update packages
      ansible.builtin.package:
        name: "*"
        state: latest

  tasks:
    - name: Ensure NordVPN installer is present on remote
      ansible.builtin.copy:
        src: ./nordvpn-install.sh
        dest: /root/nordvpn-install.sh
        mode: "0775"

    - name: Ensure NordVPN is installed
      ansible.builtin.command: /root/nordvpn-install.sh

    # Setup NordVPN at startup and ensure is started

    - name: Ensure share group exists
      ansible.builtin.group:
        name: "{{ share_group }}"
        gid: 3500
        state: present

    - name: Ensure share user exists
      ansible.builtin.user:
        name: "{{ shareuser_name }}"
        group: "{{ shareuser_name }}"
        groups: "{{ share_group }}"
        uid: 1000
        password: "{{ shareuser_password | password_hash(hashtype='sha512', salt=shareuser_salt) }}"
        state: present

    - name: Ensure share folder exists
      ansible.builtin.file:
        path: /share
        state: directory
        mode: "0775"

    - name: Ensure qBitttorrent is installed
      ansible.builtin.package:
        name: qbittorrent-nox
        state: present
