---
- name: Install Wireguard
  hosts: wireguard

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Update apt packages
      ansible.builtin.apt:
        name: ¨*¨
        state: latest

  tasks:
    - name: Ensure wireguard, iptables, and gunicorn are installed
      ansible.builtin.apt:
        name:
          - wireguard
          - iptables
          - gunicorn
        state: present

    - name: Ensure required Python packages are available
      ansible.builtin.pip:
        name:
          - ifcfg
          - flask
          - flask_qrcode
          - icmplib

    - name: Copy wg0 config file to remote
      ansible.builtin.copy:
        src: ./wg0.conf
        dest: /etc/wireguard/wg0.conf
        mode: '0644'

    - name: Enable wg0 wireguard systemd service
      ansible.builtin.systemd:
        name: wg-quick@wg0.service
        state: started
        enabled: true

    - name: Set permission of wireguard folder
      ansible.builtin.file:
        path: /etc/wireguard
        mode: '0755'
        state: directory
        recurse: true

    - name: Git clone wireguard dashboard repository
      ansible.builtin.git:
        repo: https://github.com/donaldzou/WGDashboard.git
        dest: /src/wg-dashboard
        clone: true
        update: true
        depth: 1

    - name: Set wg deamon executable
      ansible.builtin.file:
        path: /src/wg-dashboard/src/wgd.sh
        mode: u+x

    - name: Install wg dashboard
      ansible.builtin.command: /src/wg-dashboard/src/wgd.sh install
      changed_when: false

    - name: Copy wg dashboard service file to remote
      ansible.builtin.copy:
        src: ./wg-dashboard.service
        dest: /etc/systemd/system/wg-dashboard.service
        mode: '0664'

    - name: Copy wg dashboard config file to remote
      ansible.builtin.copy:
        src: ./wg-dashboard.ini
        dest: /src/wg-dashboard/src/wg-dashboard.ini
        mode: '0644'

    - name: Enable and start wg dashboard systemd service
      ansible.builtin.systemd:
        name: wg-dashboard.service
        state: started
        enabled: true
