---
- name: Initiate server
  hosts: all

  handlers:
    - name: Restart ssh
      ansible.builtin.service:
        name: sshd
        state: restarted

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Update apt packages
      ansible.builtin.apt:
        name: ¨*¨
        state: latest

  tasks:
    - name: Disable SSH password authentication
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
        validate: 'sshd -t -f %s'
      notify: Restart ssh

    - name: Set authorized ssh keys
      ansible.builtin.copy:
        src: ./authorized_keys
        dest: /root/.ssh/authorized_keys
        mode: "0644"

    - name: Ensure NTP, Git, Python3, and pip are installed
      ansible.builtin.apt:
        name:
          - ntp
          - git
          - python3
          - python3-pip
        state: present

    - name: Ensure NTP is running
      ansible.builtin.service:
        name: ntpd
        state: started
        enabled: true

    - name: Set git system name
      community.general.git_config:
        name: user.name
        scope: system
        value: "Tycho Brouwer"

    - name: Set git system email
      community.general.git_config:
        name: user.email
        scope: system
        value: "tychobrouwer33@gmail.com"

    - name: Set git system default branch
      community.general.git_config:
        name: init.defaultBranch
        scope: system
        value: "main"
